---
- name: Get Sensor Battery information.
  ansible.builtin.uri:
    url: "https://{{ hostname }}:{{ https_port }}{{ api_system }}/Oem/Dell/DellSensors/iDRAC.Embedded.1_0x23_SystemBoardCMOSBattery"
  register: battery_result
  delegate_to: "{{ idrac_gather_facts_delegate }}"

- name: Set Sensor Battery facts
  ansible.builtin.set_fact:
    "sensor_battery":
      "{{ battery_result.json | ansible.utils.remove_keys(target=['@odata.context',
      '@odata.id', '@odata.type']) }}"
  ignore_errors: true
  register: battery_result_register

- name: Set fail message
  ansible.builtin.fail:
    msg: "This target is not supported on iDRAC8"
  when: battery_result.status == 400 and battery_result.server == "iDRAC/8"
