---
- name: Get Fan information.
  ansible.builtin.uri:
    url: "https://{{ hostname }}:{{ https_port }}{{ api_chassis }}/ThermalSubsystem/Fans?$expand=*($levels=1)"
  register: fan_result
  delegate_to: "{{ idrac_gather_facts_delegate }}"
  ignore_errors: true

- name: Set Fan facts
  ansible.builtin.set_fact:
    fan: "{{ fan_result.json.Members | ansible.utils.remove_keys(target=['@odata.context', '@odata.id', '@odata.type']) }}"
  ignore_errors: true
  register: fan_result_register

- name: Set the fail message
  ansible.builtin.fail:
    msg: "This target is not supported on iDRAC8"
  when: fan_result.status == 500 and fan_result.server == "iDRAC/8"
