---
- name: Get PCIeSSDBackPlane information.
  ansible.builtin.uri:
    url: "https://{{ hostname }}:{{ https_port }}/redfish/v1/Chassis/Oem/Dell/DellPCIeSSDBackPlanes"
  register: pcie_result
  delegate_to: "{{ idrac_gather_facts_delegate }}"

- name: Set PCIeSSDBackPlane facts
  ansible.builtin.set_fact:
    backplane: "{{ pcie_result.json.Members | ansible.utils.remove_keys(target=['@odata.context', '@odata.id', '@odata.type']) }}"
  ignore_errors: true
  register: pcie_result_register

- name: Set fail message
  ansible.builtin.fail:
    msg: "This target is not supported on iDRAC8"
  when: pcie_result.status == 404 and pcie_result.server == "iDRAC/8"
